[project]
name = "weather"
version = "0.1.0"
description = "The weather MCP server for connecting to MCP client"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
